#!/bin/python3

import math
import os
import random
import re
import sys


def nonDivisibleSubset(k, s):

    rem = [0] * k

    for num in s:
        rem[num % k] += 1

    ans = min(rem[0], 1)

    for i in range(1, (k // 2) + 1):

        if i != k - i:
            ans += max(rem[i], rem[k - i])

    # special case when k is even
    if k % 2 == 0:
        ans += 1

    return ans


if __name__ == '__main__':
    first_multiple_input = input().rstrip().split()

    n = int(first_multiple_input[0])

    k = int(first_multiple_input[1])

    s = list(map(int, input().rstrip().split()))

    result = nonDivisibleSubset(k, s)

    print(result)
